name: Demonstrate CI/CD in GitHub for Flutter

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2.8.0
      - run: flutter build ipa --build-name=1.0.${{github.run_number}} --build-number=${{github.run_number}}
        name: Building application
      - uses: actions/upload-artifact@v3
        name: Archive production artifacts
        with:
          name: ios-app-1.0.${{github.run_number}}-${{github.sha}}
          path: |
            build/ios/ipa/web_view.ipa
          retention-days: 1

  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy job
        run: echo "This is a dummy job"