name: Demonstrate CI/CD in GitHub for Flutter

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - run: flutter --version
      - run: flutter build ipa --build-name=1.0.${{github.run_number}} --build-number=${{github.run_number}} --no-codesign
        name: Building application
      - name: Показать содержимое текущего каталога
        run: ls
      - name: Показать содержимое каталога
        run: ls build/ios/ipa/
      - name: Показать path
        run: pwd
      - uses: actions/upload-artifact@v3
        name: Archive production artifacts\
        with:
          name: ios-app-1.0.${{github.run_number}}-${{github.sha}}
          path: |
            build/ios/ipa/app-release.ipa
          retention-days: 1

  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy job
        run: echo "This is a dummy job"